services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - "${SERVER_PORT}:8000" # Map server port on the host to port 8000 in the container
    volumes:
      - ./tronbyt_server:/app/tronbyt_server # for development
      - ./users:/app/users # for development
      - ./data:/app/data # for development
      - "/etc/localtime:/etc/localtime:ro" # used to sync docker with host time
    environment:
      - PYTHONUNBUFFERED=1
      - SYSTEM_APPS_REPO
      - PRODUCTION
      - LOG_LEVEL
      - ENABLE_USER_REGISTRATION
      - ADMIN_PASSWORD
      - UVICORN_ACCESS_LOG=${UVICORN_ACCESS_LOG:-false}
      - WEB_CONCURRENCY
      - TRONBYT_HOST=0.0.0.0
