services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:8000" # Map server port on the host to port 8000 in the container
    volumes:
      - .:/app # for development
      - "/etc/localtime:/etc/localtime:ro" # used to sync docker with host time
    environment:
      - SERVER_HOSTNAME=${SERVER_HOSTNAME_OR_IP:?SERVER_HOSTNAME_OR_IP MUST BE SET IN .env FILE !!!!!!!!!!!!!!!!!.}
      - SERVER_PORT
      - PIXLET_RENDER_PORT1=${PIXLET_SERVE_PORT1}
      - PYTHONUNBUFFERED=1
      - SYSTEM_APPS_REPO
      - PRODUCTION=0
