services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - "${SERVER_PORT}:8000" # Map server port on the host to port 8000 in the container
    volumes:
      - ./tronbyt_server:/app/tronbyt_server # for development
      - ./users:/app/users # for development
      - ./data:/app/data # for development
      - "/etc/localtime:/etc/localtime:ro" # used to sync docker with host time
    environment:
      - SERVER_HOSTNAME=${SERVER_HOSTNAME_OR_IP:?SERVER_HOSTNAME_OR_IP MUST BE SET IN .env FILE !!!!!!!!!!!!!!!!!.}
      - SERVER_PORT
      - PYTHONUNBUFFERED=1
      - SYSTEM_APPS_REPO
      - PRODUCTION=0
      - LOG_LEVEL=DEBUG
      - MAX_USERS
