services:
  web:
    image: ghcr.io/tronbyt/server:2 # latest v2.x.x release tag
    restart: unless-stopped
    init: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro" # used to sync docker with host time
      - data:/app/data
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-${UID:-1000}}
      - SYSTEM_APPS_REPO
      - PRODUCTION
      - ENABLE_USER_REGISTRATION
      - WEB_CONCURRENCY
      - GITHUB_TOKEN

    healthcheck:
      test: ["CMD", "/app/tronbyt-server", "health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  proxy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
      - "80:80" # Always open 80/443 for the HTTP-01 challenge
      - "443:443" # comment this out if SERVER_PORT is already set to 443
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/data
    depends_on:
      - web
volumes:
  data:
