services:
  web:
    image: ghcr.io/tronbyt/server:2 # latest v2.x.x release tag
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8000}:8000" # Map server port on the host to port 8000 in the container
    init: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro" # used to sync docker with host time
      - data:/app/data
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-${UID:-1000}}
      - SYSTEM_APPS_REPO
      - PRODUCTION
      - REDIS_URL=redis://redis:6379
      - ENABLE_USER_REGISTRATION
      - WEB_CONCURRENCY
      - SINGLE_USER_AUTO_LOGIN
      - GITHUB_TOKEN

    healthcheck:
      test: ["CMD", "/app/tronbyt-server", "health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    healthcheck:
      test: "[ $$(redis-cli ping) = 'PONG' ]"
      interval: 60s
      timeout: 3s
      retries: 3
volumes:
  data:
  redis:
