services:
  web:
    image: ghcr.io/tronbyt/server:latest
    restart: unless-stopped
    user: "tronbyt:tronbyt"
    init: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro" # used to sync docker with host time
      - users:/app/users
      - data:/app/data
    environment:
      - SYSTEM_APPS_REPO
      - PRODUCTION
      - ENABLE_USER_REGISTRATION
      - WEB_CONCURRENCY
      - TRONBYT_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "python3", "/app/healthcheck.py", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  proxy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
      - "80:80" # Always open 80/443 for the HTTP-01 challenge
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/data
    depends_on:
      - web
volumes:
  users:
  data:
