services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - "${SERVER_PORT:-8000}:8000" # Map server port on the host to port 8000 in the container
    volumes:
      - ./tronbyt_server:/app/tronbyt_server # for development
      - ./users:/app/users # for development
      - ./data:/app/data # for development
      - "/etc/localtime:/etc/localtime:ro" # used to sync docker with host time
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-${UID:-1000}}
      - SYSTEM_APPS_REPO
      - PRODUCTION
      - LOG_LEVEL
      - ENABLE_USER_REGISTRATION
      - GITHUB_TOKEN
