services:
- type: web
  name: tronbyt-server
  runtime: image
  image:
    url: ghcr.io/tronbyt/server:1.5.4
  plan: free
  envVars:
  - key: WEB_CONCURRENCY
    value: "1"
  - key: TRONBYT_HOST
    value: "0.0.0.0"
version: "1"
