# v1.5.3/1.5.2 no good for render as of 2025-11-02 -tavis
services:
- type: web
  name: tronbyt-server
  runtime: image
  image:
    url: ghcr.io/tronbyt/server:1.5.1
  plan: free
  envVars:
  - key: PRODUCTION
    value: "1"
  - key: WEB_CONCURRENCY
    value: "1"
  - key: TRONBYT_HOST
    value: "0.0.0.0"
version: "1"
